${prefix}/controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    twist_controller:
      type: picknik_twist_controller/PicknikTwistController

    robotiq_gripper_controller:
      type: position_controllers/GripperActionController

    fault_controller:
      type: picknik_reset_fault_controller/PicknikResetFaultController

${prefix}/joint_trajectory_controller:
  ros__parameters:
    joints:
      - ${prefix}joint_1
      - ${prefix}joint_2
      - ${prefix}joint_3
      - ${prefix}joint_4
      - ${prefix}joint_5
      - ${prefix}joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

${prefix}/twist_controller:
  ros__parameters:
    joint: ${prefix}tcp
    interface_names:
      - twist.linear.x
      - twist.linear.y
      - twist.linear.z
      - twist.angular.x
      - twist.angular.y
      - twist.angular.z

${prefix}/robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: ${prefix}robotiq_85_left_knuckle_joint
    allow_stalling: true
